name: Spell Check
on: [push, pull_request]

env:
  # This fixes the Node.js 20 deprecation warning
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  spellcheck:
    name: Check Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Spell Check
        uses: streetsidesoftware/cspell-action@v6
        with:
          # This tells it to look for the file we just made
          config: 'cspell.json'
          files: "**/*.md"